### ISSUE TITLE
Name for this project

### ISSUE THREAD

**Issue by jbednar** [holoviz/monitor#4]
This project needs a name!  It's currently called `monitor`, which is inoffensive and accurate; it is a tool for monitoring stuff.  But `monitor` is obviously not unique or searchable, so it's not ideal as a name.  Brainstorming some other possibilities:

- variants of monitor
   - x Panel Monitor (accurate, in that it's a monitor that is based on Panel and also monitors Panel, but still unsearchable)
   - x HoloViz Monitor (searchable, but not particularly accurate; it does use some HoloViz tools, but it sounds like it's for monitoring HoloViz, while really it can monitor anything)
   - x Monitr (accurate and searchable, but sounds like R rather than Python)
   - x Monit (already in [PyPI](https://pypi.org/project/monit))
   - Onit (from monitor, and also a play on "keep an eye on it")

- watching
   - x watcher (already used in a technical sense in Param; already in [PyPI](https://pypi.org/project/watcher))
   - x watchman (sexist?; already in [PyPI](https://pypi.org/project/watchman))
   - x spotter (already in [PyPI](https://pypi.org/project/spotter)
   - x lookout (already in [PyPI](https://pypi.org/project/lookout))
   - watchkeeper

- supervising
   - x supervisor (used a lot in programming already; already in [PyPI](https://pypi.org/project/supervisor))
   - x overseer (has slavery connotations; already in [PyPI](https://pypi.org/project/overseer))
   - x warden (has prison connotations; already in [PyPI](https://pypi.org/project/warden))
   - x overlord (a bit much!; already in [PyPI](https://pypi.org/project/overlord))
   
- surveying
   - x surveyor (already in [PyPI](https://pypi.org/project/surveyor))
   - x overviewer
   - x overview 
   - x overviews (resonates with holoviews?)
   
- caretaking
   - x steward (already in [PyPI](https://pypi.org/project/steward))
   - x caretaker
   - x attendant
   - x tabwatcher
   - _ tabkeeper
   
- childcare
   - x nanny (already in [PyPI](https://pypi.org/project/nanny))
   - x daycare (already in [PyPI](https://pypi.org/project/daycare))
   - x poppins (as in Mary)
   - x nanna (as in Peter Pan)

- animals (synergizing with Python?)
   - x canary (as in a coal mine; already in [PyPI](https://pypi.org/project/canary))
   - x eagle (as in eagle eyed; already in [PyPI](https://pypi.org/project/eagle))
   - x hawk (as in watching like a hawk; already in [PyPI](https://pypi.org/project/Hawk))
   - x watchdog (already in [PyPI](https://pypi.org/project/watchdog))

- servers/apps
   - x restmonitor
   - x servemonitor
   - _ appmonitor

Anyone have other suggestions?

**Comment by jbednar** [comment]
Others suggested:

- holomon 
- argos (many-eyed watchman of Greek myth; already in [PyPI](https://pypi.org/project/argos))
- argus (variant of argos; already in [PyPI](https://pypi.org/project/argus)  and already [used for monitoring](https://en.wikipedia.org/wiki/Argus_(monitoring_software)))
- heimdall (watchman of Greek myth; already in [PyPI](https://pypi.org/project/heimdall) and as an [app dashboard](https://github.com/linuxserver/Heimdall))

**Comment by jbednar** [comment]
Philipp and I went through and put an `x` on those that we don't think are suitable for some reason, typically because it is in PyPI as a credible project or it has negative or inaccurate connotations.  Ones that aren't rejected but we aren't enthusiastica about got a `_`. Right now, that leaves `onit` and `watchkeeper` as the lead contenders.

**Comment by philippjfr** [comment]
After consulting a number of people we outvoted @jbednar and decided on Lumen. I've filed a request to get the squatter evicted from PyPI: https://github.com/pypa/pypi-support/issues/643
